### ISSUE TITLE
Fix problem where filter disappears

### ISSUE THREAD

**Issue by pritpalc** [CodetheChangeFoundation/overdosePrevention#38]
### Acceptance Criteria:
* When collapsing filter, the bar should still appear

### Steps to Reproduce:
* Click on a city
* Swipe up or click on the filter bar
* Collapse the filter bar
* Notice that the filter bar is no longer there

**Comment by vinielk** [comment]
### Issue
* Looks like this is an bug with the package we are using. The corresponding GitHub repo for the package has the fix, but the npm package doesn't.
* NPM package was last updated 10 months ago, but the fix was made in March 2019.
  * [GitHub Repo](https://github.com/react-native-vietnam/react-native-swipe-up-down)
  * [NPM Package](https://www.npmjs.com/package/react-native-swipe-up-down/v/1.0.7)

### Possible Solutions
1. Use the same package, but use the code from the GitHub repo instead of the npm package
2. Use another package

I'm not too sure which one is the best option. Thoughts @pritpalc

**Comment by pritpalc** [comment]
I think it might be best to just use the GitHub repo then, this is a pretty staple package, and I couldn't find another one that has the same capabilities.

**Comment by vinielk** [comment]
Ok thanks. I'll use the GitHub repo

**Comment by vinielk** [comment]
Took 5 hours. Debugging the bug took a lot of time because I thought there was something wrong with our code.
